### ISSUE TITLE
求ucf101的pkl数据！！

### ISSUE THREAD

**Issue by 02echo** [txyugood/PaddlePoseC3D#2]

**Comment by txyugood** [comment]
https://aistudio.baidu.com/aistudio/datasetdetail/140593

**Comment by 02echo** [comment]
谢谢！！不好意思，没认真看文件列表。




1428727443w
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "txyugood/PaddlePoseC3D"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月10日(星期一) 晚上7:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [txyugood/PaddlePoseC3D] 求ucf101的pkl数据！！ (Issue #2)





 
https://aistudio.baidu.com/aistudio/datasetdetail/140593
