### ISSUE TITLE
rgb模态和骨骼关键点模态融合

### ISSUE THREAD

**Issue by Xinxinatg** [txyugood/PaddlePoseC3D#3]
你好，请问在飞浆框架里可以实现rgb+skeleton双模态的融合吗？就像[mmaction2](https://github.com/open-mmlab/mmaction2/blob/master/configs/skeleton/posec3d/README.md)里实现的一样。如果融合了两个模态，模型的性能应该会有大的提升

**Comment by txyugood** [comment]
可以的，不过本项目没有实现这个，你可以自己参考mmaction2复现。
